### ISSUE TITLE
The `/yesboats start` command is non-functional

### ISSUE THREAD

**Issue by H2ofiremaster** [LearnerCouncil/YesBoats#18]
**Describe the bug**
The `/yesboats start` command does not function: In does not show up in tab-completion, and running it returns "Invalid arguments. Try '/yesboats help' for help."

**To Reproduce**
1. Ensure you have the  `yesboats.commands.yesboats.admin` permission
2. Run `/yesboats start`

**Expected behavior**
The command should run as described in the help menu.

**Minecraft version information**
- Minecraft Version: 1.21.1
 - Server Software: Paper
 - Server Software Version: #119
 - Plugin Version: 1.5.2

**Comment by nullcubee** [comment]
Fixed by #21
