### ISSUE TITLE
I want to use this plugin (Add README with command documentation)

### ISSUE THREAD

**Issue by LeePC** [LearnerCouncil/YesBoats#6]
I want to know how to use it, but can you tell me how to use it?

**Comment by H2ofiremaster** [comment]
Hi, sorry, I didn't actually expect anyone to find this repository. I'll be sure to add a README with installation instructions and basic documentation soon, so keep an eye out.

**Comment by LeePC** [comment]
I want to use it as streaming content, but is it okay??

But I want to know how to use it

**Comment by H2ofiremaster** [comment]
Yes, you are free to use this plugin. Some basic instructions on how to use it can be found in the [README](https://github.com/LearnerCouncil/YesBoats/blob/main/README.md), and you can feel free to ask about anything specific.

**Comment by LeePC** [comment]
I'm sorry, but don't you have a video tutorial video?
I didn't understand

**Comment by H2ofiremaster** [comment]
No. I'm sorry. I don't currently have a tutorial video. Was there a specific aspect that you didn't understand, or did you just not understand it in general?

**Comment by NullCub3** [comment]
I'm going to close this issue as we've added information on what the commands and functions do to the README. Beyond that I would recommend looking up a tutorial on how to set up a Minecraft server with Spigot or Paper and install plugins on it, that will get you most of the way. We just don't have the resources to make a tutorial video for this plugin right now. Best of luck with your streaming endeavors!
